### ISSUE TITLE
Stuff todo

### ISSUE THREAD

**Issue by MaybeMaru** [MaybeMaru/Maru3D-OTLA#1]
### Stuff for 0.4 or 0.5
- [x] Add check boxes stuff
- [x] Make the converter look better
- [x] Add .mtl format compatibility (for textures and materials)

**Comment by MaybeMaru** [comment]
shit is done, update commit to the github soon
